server:
    port: 80
    servlet:
        context-path: '/test2'
    tomcat:
        accesslog:
            encoding: UTF-8
spring:
    datasource:
        name: 'root1'
        password: '4444'
        url: '..............'
        hikari:
            idle-timeout: 10000000
            max-lifetime: 1000
            minimum-idle: 100

    profiles:
        #        active: dev
        default: default
