server:
    port: 80
    servlet:
        context-path: '/test'
    tomcat:
        accesslog:
            encoding: UTF-8
spring:
    datasource:
        name: 'root'
        password: '111111'
        url: '...'
        hikari:
            idle-timeout: 10000
            max-lifetime: 10
            minimum-idle: 10
