server:
    port: 80
    servlet:
        context-path: '/test2'
    tomcat:
        accesslog:
            encoding: UTF-8
spring:
    datasource:
        name: 'root1'
        password: '33333'
        url: '.........'
        hikari:
            idle-timeout: 10000000
            max-lifetime: 10
            minimum-idle: 10
