server:
    port: 80
    servlet:
        context-path: '/test'
    tomcat:
        accesslog:
            encoding: UTF-8
spring:
    datasource:
        name: 'root1'
        password: '22222'
        url: '......'
        hikari:
            idle-timeout: 100000
            max-lifetime: 10
            minimum-idle: 10
